import type { LucideIcon } from "lucide-react";
import {
  AirVent,
  Bath,
  BedDouble,
  CarFront,
  Coffee,
  CookingPot,
  Droplets,
  Home,
  Leaf,
  Microwave,
  Mountain,
  Refrigerator,
  Sparkles,
  Star,
  Sun,
  Trees,
  Tv,
  Users,
  Waves,
  Wifi,
  Wind,
} from "lucide-react";
import type { IconName } from "@/types/dome";

export const icons: Record<IconName, LucideIcon> = {
  users: Users,
  bed: BedDouble,
  bath: Bath,
  jacuzzi: Waves,
  utensils: CookingPot,
  wifi: Wifi,
  car: CarFront,
  coffee: Coffee,
  snowflake: AirVent,
  tv: Tv,
  sun: Sun,
  droplets: Droplets,
  microwave: Microwave,
  refrigerator: Refrigerator,
  wind: Wind,
  sparkles: Sparkles,
  leaf: Leaf,
  home: Home,
  mountain: Mountain,
  trees: Trees,
  star: Star,
};
